fixed #16 - Implement progress bar for subtree processing
firefox-devtools/webcompat-helper pull request #18
Opened 2019-08-07 08:56 UTC by dadaa

2019-08-09 09:00 UTC, captainbrosset requested changes
Wow, that is pretty impressive to read. I was not expecting the progress bar to actually move accurately! 😱 

There are a few reasons why I think we might *not* want to do this though:

* this code is quite complex to understand at first sight (maybe not hard to maintain though, so that might be ok)
* maybe my laptop is just too powerful, but it's hard to see the progress bar for more than an instant
* the code is inside the experimental API which is something that only works on Firefox and not in other browsers.

So, because of these reasons I would be tempted to add an infinite spinner instead of a progress bar.
With a spinner everything becomes much simpler. No experimental API code to write. You just start it when a node is selected, and you remove it when the warnings are returned.

Now, I do like the accuracy of this progress bar, and on lower-end machines, it might actually become more important for it to be displayed like this.

The other counter-argument to what I said is: on other browsers that don't support this API, we could always show a different loader, and only have this one on Firefox.

So I'm not against landing this per say. I just think that we could achieve a similar result with way less code 😄

2019-08-09 09:00 UTC, captainbrosset commented on extension/sidebar-pane.js
> +  progressBar.setText("Get all of node in the subtreep");
Maybe rephrase to `Getting all descendants of the selected node`.

2019-08-09 09:00 UTC, captainbrosset commented on extension/experiments/inspectedNode/api-client.js
> +      addListener(listener) {
Can you please add a bit of code comments here to explain what is going on? 
This progress listener code is quite complicated, and a comment would help a lot.

2019-08-09 09:00 UTC, captainbrosset commented on extension/experiments/inspectedNode/api-client.js
> +      removeListener(listener) {
Same here.

2019-08-09 09:00 UTC, captainbrosset commented on extension/progress-bar.js
> +  incremental(value) {
Just `increment` would be fine.

2019-08-09 09:00 UTC, captainbrosset commented on extension/progress-bar.js
> +class ProgressBar {
Please add a short jsdoc comment that explains what `parentEl`, `labelEl` and `progressEl` should be.
And also how to use this class. What do `enable` and `disable` do, etc.

2019-08-09 09:00 UTC, captainbrosset commented on extension/sidebar-pane.js
> +  progressBar.setMax(nodes.length + 2);
Why `+2` here?

2019-08-09 09:00 UTC, captainbrosset commented on extension/sidebar-pane.js
> +  progressBar.setText("Get compatibility for nodes");
Maybe rephrase to `Getting web compatibility issues for elements`.

2019-08-09 09:00 UTC, captainbrosset commented on extension/sidebar-pane.js
> +  progressBar.setText("Observe getting applied styles");
`Getting the applied CSS styles for all elements`

2019-08-09 09:00 UTC, captainbrosset commented on extension/sidebar-pane.js
> +  progressBar.setText("Get compatibility for styles");
`Getting web compatibility issues for CSS styles`.

2019-08-09 09:00 UTC, captainbrosset commented on extension/sidebar-pane.js
> +  progressBar.setText("Render all issues");
`Rendering all issues`.

2019-08-09 17:24 UTC, oslego commented
First, let me say that this is awesome! I really appreciate your diligence with showing an accurate progress indicator, @dadaa!

But after carefully reading the code, I echo Patrick's concerns.

The progress indicator is fantastic, but on our machines (which are quite powerful, yes) the indicator is barely visible. Any meaningful delay would come from inspecting a very complex and very deeply nested DOM due to the recursive child traversal.

Fortunately, [we have a Talos test](https://searchfox.org/mozilla-central/source/testing/talos/talos/tests/devtools/addon/content/pages/custom/inspector/index.html) for this sort of scenario to check DevTools performance (you can download the file and run it on a local server). It generates 50 levels of nesting under the first node. That's pretty extreme, but even in this scenario, the action is almost instant and the indicator is barely visible. 

As Patrick says, it may be more beneficial on slower machines, but I'd argue in that case that any additional computational overhead is adding yet more slowness to the process with the event handling and DOM manipulation for the progress indicator itself.

Given the added complexity and the hard dependency on the experimental API (which we may not be able to use if we port this extension to another browser), I agree with Patrick that a sensible approach for ourselves and future maintainers would be to take the easy route and use an indeterminate loading spinner (achievable perhaps still with a `<progress>` element and the [`:indeterminate` CSS pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate))

I can understand you worked hard on this and you're proud of it. You should be, it's amazing!
 
But I encourage keeping code complexity low so we have room in future developers' heads so they can grasp what's going on with the business logic without getting confused by the progress indicator which, in this case, while great, it seems to be mostly invisible to users on reasonably-powered machines.

My suggestion would be to not merge this patch, but still keep it around. If we discover that there are viable cases where a highly accurate progress indicator is required for categorically improving user experience, then we should use it and accept the complexity then.

2019-08-13 00:37 UTC, dadaa commented
Thank you so much @captainbrosset and @oslego !
Yep, I understand your concern. 
I'll keep this PR as it is and create one more PR which fixes by another simple way.

2024-07-23 13:57 UTC, closed without merging